version: "3"
services:
  auth:
    image: auth-api
    build: ./auth-api
  users:
    image: users-api
    build: ./users-api
    ports: 
      - "8080:8080"
  tasks:
    image: tasks-api
    build: ./tasks-api
    ports: 
      - "8000:8000"
    environment:
      TASKS_FOLDER: tasks
    
