apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  # ClusterIP (default), NodePort, LoadBalancer, ExternalName
  # 為了讓這個 service 可以被外部存取，所以改成 LoadBalancer，因為預設的 ClusterIP 只能在 cluster 內部存取
  type: LoadBalancer # LoadBalancer 是唯一既能夠被 cluster 外部存取，又能夠被 cluster 內部存取的 service type
  ports:
    - protocol: TCP
      port: 80 # 參考 ../frontend/conf/nginx 裡面 listen 80，應用程式 proxy 監聽的 port
      targetPort: 80 # 參考 ../frontend/Dockerfile 裡面的 EXPOSE 80 對外開放的 port