apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks
  # ClusterIP (default), NodePort, LoadBalancer, ExternalName
  # 為了讓這個 service 可以被外部存取，所以改成 LoadBalancer，因為預設的 ClusterIP 只能在 cluster 內部存取
  type: LoadBalancer # LoadBalancer 是唯一既能夠被 cluster 外部存取，又能夠被 cluster 內部存取的 service type
  ports:
    - protocol: TCP
      port: 8000 # 參考 tasks-api/tasks-app.js 裡面 app.listen(8000)，應用程式監聽的 port
      targetPort: 8000 # 參考 tasks-api/Dockerfile 裡面的 EXPOSE 8000，container 對外開放的 port